# Generated by Django 4.2.3 on 2023-09-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Тема')),
                ('slug', models.SlugField(max_length=75, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тема вопросов',
                'verbose_name_plural': 'Темы вопросов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('status', models.BooleanField(default=False, verbose_name='Вопрос отвечен ')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопросы/Ответы',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
    ]
