# Generated by Django 4.2.3 on 2023-09-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='car_model',
        ),
    ]
