# Generated by Django 4.2.3 on 2023-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_remove_tariff_car_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('pk',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_km',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Цена за километр'),
        ),
    ]
