# Generated by Django 4.2.3 on 2023-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0004_alter_tariff_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs/', verbose_name='Изображение'),
        ),
    ]
