# Generated by Django 4.2.3 on 2023-10-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_tariff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='marks',
            field=models.CharField(default='', max_length=255, verbose_name='Марки тарифа'),
        ),
    ]
