# Generated by Django 4.2.3 on 2023-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0006_tariff_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL к изображению'),
        ),
    ]
