# Generated by Django 4.2.3 on 2023-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0010_alter_tariff_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('sequence',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='tariff',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок отображения на сайте'),
        ),
    ]
