version: '3'
services:
  crosscity_db:
    image: postgres:15
    ports:
      - 5432:5432 # 32704 внешний порт для подключения к бд
    volumes:
      - /var/lib/cross_city_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - cross_network
#  cross_city_app:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    container_name: cross_city_app
#    restart: always
#    environment:
#      - DB_USER=$DB_USER
#      - DB_PASSWORD=$DB_PASSWORD
#      - DB_NAME=$DB_NAME
#      - DB_HOST=crosscity_db
#      - SECRET_KEY=$SECRET_KEY
#    ports:
#      - 13001:8000
networks:
  cross_network:
    driver: bridge