version: '3'
services:
  crosscity_test_db:
    image: postgres:15
    ports:
      - 5432:5432 # 32704 внешний порт для подключения к бд
    volumes:
      - /var/lib/test_cross_city_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

