# Generated by Django 4.2.3 on 2023-10-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Мои контакты', 'verbose_name_plural': 'Мои контакты'},
        ),
    ]
