# Generated by Django 4.2.3 on 2023-11-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='type_vacancy',
        ),
        migrations.DeleteModel(
            name='TypeVacancy',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
