# Generated by Django 4.2.3 on 2023-11-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('phone_number', models.CharField(blank=True, default='', max_length=25, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, default='', max_length=60, verbose_name='email')),
                ('message', models.TextField(max_length=500, verbose_name='Обращение')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитан')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата обращения')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ('read',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя отправителя')),
                ('message', models.TextField(max_length=500, verbose_name='Отзыв')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('publish', models.BooleanField(default=False, verbose_name='Допустим к публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('publish', '-date'),
            },
        ),
    ]
