# Generated by Django 4.2.3 on 2023-09-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя водителя')),
                ('contact', models.CharField(max_length=25, verbose_name='Телефон водителя')),
                ('car', models.CharField(max_length=100, verbose_name='Машина')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ('name',),
            },
        ),
    ]
