# Generated by Django 4.2.3 on 2023-11-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
    ]
