# Generated by Django 4.2.3 on 2023-09-08 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100, verbose_name='Место отправления')),
                ('to_place', models.CharField(max_length=100, verbose_name='Место прибытия')),
                ('distance', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Дистанция в км.')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('contact', models.CharField(max_length=150, verbose_name='Средство связи с клиентом')),
                ('remark', models.CharField(max_length=255, verbose_name='Примечания к заказу')),
                ('baby_chair', models.BooleanField(default=False, verbose_name='С детским креслом или нет')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена поездки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('ready', 'Готов к исполнению'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=12, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Заказ создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Заказ обнавлён')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Скидка не может быть меньше 0%'), django.core.validators.MaxValueValidator(100, message='Скидка не может быть больше 100%')], verbose_name='Процент скидки')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver', verbose_name='Водитель')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-departure_time',),
            },
        ),
    ]
