# Generated by Django 4.2.3 on 2023-09-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created', '-departure_time'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
